name: Queued Workflow Test
permissions: write-all
on: [push]

default:
  run:
    timeout-minutes: 1
jobs:
  queued-job:
    runs-on: ubuntu-latest
    steps:
      - name: Start Job
        run: echo "Job started, simulating queue state..."
      
      - name: Simulate Queued State
        run: sleep 120  # Sleep for 10 minutes

      - name: Finish Job
        run: echo "Job completed after waiting."
