name: Manual Approval Workflow

on:
  workflow_dispatch:

jobs:
  wait-for-approval:
    runs-on: ubuntu-latest
    environment: "staging"  # Requires manual approval if enabled
    steps:
      - name: Pending Approval
        run: echo "Waiting for manual approval before proceeding..."
