name: Queued Workflow Test

on:
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  queued-job:
    runs-on: ubuntu-latest
    steps:
      - name: Start Job
        run: echo "Job started, simulating queue state..."
      
      - name: Simulate Queued State
        run: sleep 600  # Sleep for 10 minutes

      - name: Finish Job
        run: echo "Job completed after waiting."