name: My Awesome Workflow

on:
  push:


jobs:
  job-one:
    # This job gets a timeout of 60 minutes as set by the global attribute
    runs-on: ubuntu-latest
    steps:
      - name: my awesome step
        run: echo foo
  job-two:
    # This job gets a timeout of 60 minutes as set by the global attribute
    runs-on: ubuntu-latest
    steps:
      - name: my awesome step
        run: echo bar
  job-three:
    # This job gets a timeout of 5 minutes as set by the job level override
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - name: my awesome step
        run: echo baz